# Place any default configuration for solr_wrapper here
# port: 8983
url: https://archive.apache.org/dist/lucene/solr/7.5.0/solr-7.5.0.zip
validate: false
instance_dir: tmp/solr
download_dir: tmp/solr
collection:
  dir: solr/conf/
  name: blacklight-core
